services:
  redis-sentinel:
    image: bitnami/redis-sentinel:6.2.7
    environment:
      - REDIS_MASTER_PASSWORD=${NMA_REDIS_PASSWORD}
      - REDIS_MASTER_SET=${NMA_REDIS_MASTER_SET}
    depends_on:
      - redis
      - redis-slave
    ports:
      - "26379-26381:26379"

  redis:
    image: bitnami/redis:6.2.7
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${NMA_REDIS_PASSWORD}
    ports:
      - 6379
    volumes:
      - redis_master_data:/data

  redis-slave:
    image: bitnami/redis:6.2.7
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=${NMA_REDIS_PASSWORD}
      - REDIS_PASSWORD=${NMA_REDIS_PASSWORD}
    ports:
      - 6379
    depends_on:
      - redis
    volumes:
      - redis_slave_data:/data

  server:
    restart: always
    build:
      context: .
    env_file:
      - $ENV
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: python -m uvicorn main:app --reload --host 0.0.0.0 --port 8001
    depends_on:
      - redis

  db_admin:
    image: yandexmiddleteamv1/netflix-admin-db:latest
    environment:
      - POSTGRES_USER=${NA_DB_USER}
      - POSTGRES_PASSWORD=${NA_DB_PASSWORD}
      - POSTGRES_DB=${NA_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_admin:/var/lib/postgresql/data/

  server_admin:
    platform: linux/amd64
    restart: always
    image: yandexmiddleteamv1/netflix-admin:latest
    env_file:
      - $ENV
    ports:
      - "8000:8000"
    depends_on:
      - db_admin

  redis_etl:
    image: "redis:alpine"
    expose:
      - 6379
    volumes:
      - redis_data_etl:/data

  elasticsearch_etl:
    image: elasticsearch:7.17.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - es_data_etl:/usr/share/elasticsearch/data
    depends_on:
      - redis_etl

  kibana_etl:
    image: kibana:7.17.2
    volumes:
      - kibana_data_etl:/usr/share/kibana/data
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch_etl:9200
    depends_on:
      - elasticsearch_etl

  etl:
    platform: linux/amd64
    restart: always
    image: yandexmiddleteamv1/netflix-etl:latest
    env_file:
      - $ENV
    depends_on:
      - db_admin
      - redis_etl
      - elasticsearch_etl
      - kibana_etl

volumes:
  redis_master_data:
  redis_slave_data:
  postgres_data_admin:
  redis_data_etl:
  es_data_etl:
  kibana_data_etl:
